### ISSUE TITLE
关于github上项目

### ISSUE THREAD

**Issue by lyxia2010** [fanrunqi/AndroidInterview#1]
您好，您上传的安卓面试题，编码格式能改一下吗，下载到本地文件名都是乱码，谢了！

**Comment by fanrunqi** [comment]
你好，我刚下载了，没有问题。我用的是markdownpad2

**Comment by Natanic** [comment]
我只能在线看  下载下来客户端打开始各种编码 markdown格式的

2016-06-23 18:06 GMT+08:00 fanrunqi <notifications@github.com>:

> 你好，我刚下载了，没有问题。我用的是markdownpad2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fanrunqi/AndroidInterview/issues/1#issuecomment-228006203>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKYQYkP4aKHWr_M6Z77vO6ZGXdlJ-cq_ks5qOlqtgaJpZM4I8pBN>
> .
>



-- 
遥远  虚幻

**Comment by fanrunqi** [comment]
我看一下是什么问题，你先在线看吧

**Comment by lyxia2010** [comment]
您有Q吗，我加您吧，以后好跟你请教交流。如果实在不方便就算了




superjuior16@163.com
 
发件人： fanrunqi
发送时间： 2016-06-24 09:05
收件人： fanrunqi/AndroidInterview
抄送： lyxia2010; Author
主题： Re: [fanrunqi/AndroidInterview] 关于github上项目 (#1)
我看一下是什么问题，你先在线看吧
―

**Comment by fanrunqi** [comment]
android 相关的文章基本都是我原创的，你有什么问题可以在我博客下面留言
